Clipster/Clipster/Domain/Model/Clip.swift
Clipster/Clipster/Domain/Model/Folder.swift
Clipster/Clipster/Domain/Model/URLMetadata.swift

[Feat] Domain Enitity Schema 정의

---

Clipster/Clipster/Data/Model/ClipEntity.swift
Clipster/Clipster/Data/Model/Clipster.xcdatamodeld/Clipster.xcdatamodel/contents
Clipster/Clipster/Data/Model/FolderEntity.swift
Clipster/Clipster/Data/Model/URLMetadataEntity.swift
Clipster/Clipster/Domain/Model/Clip.swift
Clipster/Clipster/Domain/Model/Folder.swift
Clipster/Clipster/Domain/Model/URLMetadata.swift

close #11
- udpatedAt -> updatedAt 오타 수정
- CoreData에서 사용할 모델 스키마 정의(Clipster.xcdatamodeld)
- ClipEntity, URLMetadataEntity, FolderEntity 정의
- 기획 변경에 따른 URLMetadata에서 body 항목 삭제(Domain Entity에서도 삭제)
- 기획 변경에 따른 Folder에 depth 항목 추가(Domain Entity에서도 추가)

[Feat/#11] CoreData 모델 설계

---

Clipster/Clipster/App/Derived/Info.plist
Clipster/Clipster/App/Source/SceneDelegate.swift

[Feat/#20] 앱 라이트 모드 고정

---

Clipster/Clipster/App/Source/SceneDelegate.swift
Clipster/Clipster/Data/Error/CoreDataError.swift
Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
Clipster/Clipster/Data/Protocol/Persistence/ClipStorage.swift
Clipster/Clipster/Data/Repository/DefaultClipRepository.swift
Clipster/Clipster/Domain/Protocol/Repository/ClipRepository.swift
Clipster/Clipster/Domain/Protocol/UseCase/FetchClipUseCase.swift
Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchClipUseCase.swift
Clipster/Clipster/Presentation/Model/ClipDisplay.swift
Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift

close #33
- SceneDelegate에 있는 trailing whitespace 제거
- 불필요한 import 구문 제거

[Feat] 컨벤션에 맞게 코드 수정

---

Clipster/Clipster/Presentation/Scene/EditFolder/ViewModel/EditFolderViewModel.swift

close #8 
EditViewModel 설계
- Action/State와 마찬가지로 ViewModel 협의 후 리팩토링 예정

[Feat] EditFolderViewModel 설계

---

Clipster/Clipster/Domain/Protocol/UseCase/Folder/CreateFolderUseCase.swift
Clipster/Clipster/Domain/Protocol/UseCase/Folder/UpdateFolderUseCase.swift
Clipster/Clipster/Domain/UseCase/Folder/DefaultCreateFolderUseCase.swift
Clipster/Clipster/Domain/UseCase/Folder/DefaultUpdateFolderUseCase.swift
Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
Clipster/Clipster/Presentation/Scene/EditFolder/ViewModel/EditFolderViewModel.swift

close #45 
- 폴더 추가 기능
- 폴더 편집 기능

[Feat] EditFolder 기능 구현

---

Clipster/Clipster/Presentation/Model/ClipCellDisplay.swift
Clipster/Clipster/Presentation/Model/FolderCellDisplay.swift
Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Clipster/Clipster/Presentation/Util/Mapper/CellDisplayMapper.swift

close #100
현재 Hashable을 채택하고 있는 FolderCellDisplay, ClipCellDisplay의 속성들로는 unique를 구분하기 어려운 경우의 수가 있어서 UUID도 같이 가지도록 수정

[Feat] CellDisplay 스키마 변경

---

Clipster/Clipster/Presentation/Scene/Common/View/FolderRowView.swift

close #104 
폴더 공통 컴포넌트 구현
우선은 공통 컴포넌트만 작업했고, 기존 셀 등에 적용하지는 않았습니다.

[Feat] 폴더 공통 컴포넌트 구현

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/App/Source/SceneDelegate.swift
Clipster/Clipster/Domain/UseCase/URLMetadata/DefaultParseURLMetadataUseCase.swift
Clipster/Clipster/Domain/UseCase/URLValidation/DefaultCheckVaildityUseCase.swift

close #115 
- DIContainer 구현
- 혹시나 나중에 테스트할때 편하지 않을까 싶어 context를 생성자에서 주입 가능하도록 구현

[Feat] DIContainer 구현

---

Clipster/Clipster/Presentation/Scene/Common/Button/BackButton.swift
Clipster/Clipster/Presentation/Scene/Common/Button/SelectButton.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/Cell/FolderSelectorCell.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorNavigationView.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
Clipster/Clipster/Presentation/Util/Extension/UITableViewCell+Extension.swift

close #80 
폴더 선택 UI 구현
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/c472d4af-e1d8-4a42-a2d0-1e65c7fe2d41" width="250px"> |
기본 내비게이션 바는 높이가 작아 커스텀 내비게이션으로 구현했습니다.

[Feat] 폴더 선택 UI 구현

---

Clipster/Clipster/Presentation/Scene/FolderSelector/ViewModel/FolderSelectorViewModel.swift

[Feat] 폴더 선택 상태 정의

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/App/Source/SceneDelegate.swift
Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift

close #131 
DIContainer 구현에 따른 VC 변경
DIContainer에도 일부 메서드 수정이 있습니다.

[Feat] 각 VC에 DIContainer 구현사항 적용

---

Clipster/Clipster/Presentation/Scene/Common/Cell/ClipGirdCell.swift
Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift

close #119 
- ClipGridCell UI 구현
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/19e8e19a-9009-4e10-aa9e-5a563fec6d28" width="250px"> |
UILabel은 세로정렬 top을 지원하지 않아서 UITextView로 구현

[Feat] ClipGridCell UI 구현

---

Clipster/Clipster/Presentation/Scene/Common/Cell/ClipCell.swift
Clipster/Clipster/Presentation/Scene/Common/Cell/FolderCell.swift
Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift

close #130 
- ClipCell, FolderCell을 TableViewCell로 변경
- 변경에 따른 임시 주석처리
주석 처리된 부분은 이후 마이그레이션 진행하겠습니다

[Feat] ClipCell, FolderCell을 TableViewCell로 변경

---

Clipster/Clipster/Presentation/Scene/Common/Button/SaveButton.swift
Clipster/Clipster/Presentation/Scene/Common/Button/SelectButton.swift
Clipster/Clipster/Presentation/Scene/EditFolder/ViewModel/EditFolderViewModel.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorNavigationView.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/ViewModel/FolderSelectorViewModel.swift

close #143 
1. 클립 선택 화면에서는 홈 화면 선택 비활성화
2. 폴더 선택 화면에서는 홈 화면 선택 활성화

[Feat] 조건에 따른 폴더 선택 버튼 비활성화 구현

---

Clipster/Clipster/Presentation/Scene/Common/Cell/TableHeaderView.swift
Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/CollectionHeaderView.swift
Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift

close #154 
- 기존 SectionHeaderView 파일 위치 수정 및 이름 변경
- TableHeaderView 구현

[Refactor] TableHeaderView 구현

---

Clipster/Clipster/Presentation/Model/ClipDisplay.swift
Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
Clipster/Clipster/Presentation/Scene/ClipDetail/ViewModel/ClipDetailViewModel.swift
Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift

close #155 
- 데이터 바인딩
- 요구사항 변경으로 인한 ClipDisplay 모델 수정

[Feat] 클립 상세 화면 데이터 바인딩

---

Clipster/Clipster.xcodeproj/project.pbxproj

[FEAT] PROVISIONING 갱신

---

Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift

close #66 
- EditClipVIew 네비게이션 공통 뷰 추가
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/150d36df-8888-4929-9c38-6254c50df754" width="250px"> |

[Feat]: EditClipView 네비게이션 공통 뷰 추가

---

Clipster/Clipster/Presentation/Resource/Color.xcassets/White/Contents.json
Clipster/Clipster/Presentation/Resource/Color.xcassets/White/White800.colorset/Contents.json
Clipster/Clipster/Presentation/Resource/Color.xcassets/White/White900.colorset/Contents.json
Clipster/Clipster/Presentation/Resource/Icon.xcassets/FolderPlus.imageset/Contents.json
Clipster/Clipster/Presentation/Resource/Icon.xcassets/FolderPlus.imageset/folder-plus.svg
Clipster/Clipster/Presentation/Resource/Icon.xcassets/TrashWhite.imageset/Contents.json
Clipster/Clipster/Presentation/Resource/Icon.xcassets/TrashWhite.imageset/trash-2.svg

close #171
Design System 변경에 따른 아이콘, 색상 에셋 추가

[Feat] Asset 항목 추가

---

Clipster/Clipster.xcodeproj/project.pbxproj

close #173 
- 최소 요구 버전 iOS 16.0
- iOS, iPad 지원

[Refator] ShareExtension 최소 요구 iOS 버전 및 지원 기기 변경

---

Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift

close #177 
- 홈화면에서 폴더 안보이는 버그 수정

홈화면에서 폴더 안보이는 버그 수정

---

Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/Cell/FolderSelectorCell.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift

close #185 
FolderCell과 FolderSelectorCell 분리

FolderCell과 FolderSelectorCell 분리

---

Clipster/Clipster/Presentation/Resource/Icon.xcassets/Empty.imageset/Contents.json
Clipster/Clipster/Presentation/Resource/Icon.xcassets/Empty.imageset/empty.svg
Clipster/Clipster/Presentation/Scene/Common/View/EmptyView.swift

close #103
- Empty 아이콘 에셋 추가
- EmptyView 구현
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/82baa40b-0d2a-45ec-aaa1-dca344a5858a" width="250px"> |
Figma 상으로는 Line Height와 Letter Spacing도 설정해야 하는데, 디자인이 바뀔 확률이 높아보여서 생략했습니다.

EmptyView 구현

---

Clipster/Clipster/Data/Persistence/DefaultFolderStorage.swift

close #202 
기존에 fetch할 때 deletedAt == nil 항목이 있긴 있었는데, 하위 항목에 대해서는 필터링이 없었어서 수정했습니다.

soft-deleted 항목을 fetch하지 않도록 수정

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/Data/Error/CoreDataError.swift
Clipster/Clipster/Data/Persistence/CoreDataStack.swift
Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
Clipster/Clipster/Data/Persistence/DefaultFolderStorage.swift
Clipster/Clipster/Data/Protocol/Persistence/ClipStorage.swift
Clipster/Clipster/Data/Protocol/Persistence/FolderStorage.swift
Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift
Clipster/Clipster/Data/Repository/Folder/DefaultFolderRepository.swift
Clipster/Clipster/Domain/Protocol/Repository/Clip/ClipRepository.swift
Clipster/Clipster/Domain/Protocol/Repository/Folder/FolderRepository.swift
Clipster/Clipster/Domain/UseCase/Clip/DefaultCreateClipUseCase.swift
Clipster/Clipster/Domain/UseCase/Clip/DefaultDeleteClipUseCase.swift
Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchClipUseCase.swift
Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchUnvisitedClipUseCase.swift
Clipster/Clipster/Domain/UseCase/Clip/DefaultUpdateClipUseCase.swift
Clipster/Clipster/Domain/UseCase/Folder/DefaultCreateFolderUseCase.swift
Clipster/Clipster/Domain/UseCase/Folder/DefaultDeleteFolderUseCase.swift
Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchFolderUseCase.swift
Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchTopLevelFoldersUseCase.swift
Clipster/Clipster/Domain/UseCase/Folder/DefaultUpdateFolderUseCase.swift

close #205
CoreData 비동기 동작으로 개선

CoreData 비동기 동작으로 개선

---

Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
Clipster/Clipster/Presentation/Scene/Common/Button/AddButton.swift
Clipster/Clipster/Presentation/Scene/Common/Button/BackButton.swift
Clipster/Clipster/Presentation/Scene/Common/Button/DeleteButton.swift
Clipster/Clipster/Presentation/Scene/Common/Button/EditButton.swift
Clipster/Clipster/Presentation/Scene/Common/Button/InfoButton.swift
Clipster/Clipster/Presentation/Scene/Common/Button/SaveButton.swift
Clipster/Clipster/Presentation/Scene/Common/Button/SelectButton.swift
Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift

close #208 
버튼 터치 영역 수정
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/bfbd87ba-4bac-42c9-bcf9-7ed8e2a9e06f" width="250px"> |

버튼 터치 영역 수정

---

Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift
Clipster/Clipster/Presentation/Scene/Common/TextField/CommonTextField.swift
Clipster/Clipster/Presentation/Scene/EditClip/Subview/StackView/URLValidationStackView.swift
Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift

close #88 
- EmptyView 추가
- UI-프로토타입 동기화
- URL 입력 시 trim으로 UseCaes 전달
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/0180b84e-32b7-4e99-855d-70d9bbb91b8f" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/9a819381-123c-4f9b-9750-94083f740937" width="250px"> |

EditClipView UI 프로토타입 동기화

---

Clipster/Clipster/Presentation/Resource/Icon.xcassets/Empty.imageset/empty.svg
Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift

close #220 
- 홈화면 EmptyView 적용 및 Alert
- SFSafariViewController 구현

홈화면 EmptyView 적용 및 Alert

---

Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift

close #223 
빈화면 클릭 시 키보드 숨김
https://github.com/user-attachments/assets/11ffedb1-369d-4334-870f-f42b8cc855c7

폴더 추가/편집 화면에서 빈화면 클릭 시 키보드 숨김

---

Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift

close #221 
close #235 
- 폴더섹션만 있을경우 indexPath.section이 0이 되어 발생한 문제
- 폴더섹션만 있을경우에도 무조건 1이되도록 수정
- 폴더섹션은 상세정보 메뉴 제거
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/63c2148d-8b9e-4693-897d-b8738095de7e" width="250px"> |

폴더 섹션만 있을경우 문제 해결

---

Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift

close #224 
- 스크롤 뷰 적용 - EmptyView 있을 경우 하단 잘림 방지
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/bbc80948-de63-4067-899c-c60faaaadfba" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/7d86db60-c8b1-4e18-a6bd-b9df132e32f1" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/c4a8679a-cfc4-4876-9fb2-3549e7877163" width="250px"> |

EditClipView ScrollView 적용

---

Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift

close #252 
- constrants 수정
| 실행 기기 | 스크린샷(또는 GIF) | 비고 |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/8b8bdb5a-eda5-4131-aa41-f2fffe5451fa" width="250px"> | |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/2ee416ff-6c6c-42fb-9798-7f8b2bb81a1e" width="250px"> | chevronImage 반영 |

클립 추가 화면에서 폴더 label trailing 제약 조건 추가

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewModel/UnvisitedClipListViewModel.swift

close #239 
- 홈화면 방문시간 업데이트
- 방문하지 않은 클립 뷰 방문시간 업데이트
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/4e62472e-a00f-4ce7-b1cc-77bcdcc25ac5" width="250px"> |

홈화면, 방문하지 않은 클립 뷰 방문시간 업데이트

---

Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift

close #288 
- 홈, 폴더, 방문하지 않은 클립뷰 Diff 애니메이션 fasle
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/70b44c5c-448e-4f56-8498-7908000b8c01" width="250px"> |

fix: animatingDifferences 변경

---

Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
Clipster/Clipster/Presentation/Scene/Common/TextField/CommonTextField.swift
Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift

fix: 텍스트 필드 피그마 디자인 반영

---

Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift

close #282 
- 키보드 타입 변경 및 소문자만 적용

클립 편집 URL 입력 키보드 타입 변경 및 소문자 적용

---

Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift

URL 적합성 여부 관련 이미지 안 사라지는 문제 해결

---

Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift

close #215 
내비게이션 타이틀 정렬 문제 수정
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/2b4a568a-b510-44e2-86ef-d4df7039f275" width="250px"> |

내비게이션 타이틀 정렬 문제 수정

---

Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift

close #300 
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/b84e72e6-a327-41be-994b-2ec3b3abcc21" width="250px"> |

폴더 제목 글자수 제한 label 가운데 정렬

---

Clipster/Clipster/App/Source/SceneDelegate.swift
Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
Clipster/Clipster/Presentation/Scene/Common/Cell/FolderListCell.swift
Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift

close #301 
- 색상 적용 안된 부분 수정
- 맡은 화면 위주로 확인해주세요
- linkLabel은 혹시나 MVP 이후에 추가될수도 있을거 같아서 냅두긴했습니다.

색상 적용 안된 부분 수정

---

Clipster/Clipster/Presentation/Scene/Common/Cell/ClipCell.swift
Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift
Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift

close #312 
-ClipCell 배경색상 설정 및 Cell 재사용될때 image = nil 처리

ClipCell 배경색상 설정

---

Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
Clipster/Clipster/Presentation/Scene/Common/View/MemoView.swift
Clipster/Clipster/Presentation/Scene/Common/View/ThumbnailView.swift
Clipster/Clipster/Presentation/Scene/Common/View/URLView.swift
Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
Clipster/Clipster/Presentation/Util/Mapper/FolderDisplayMapper.swift

close #304 
피그마 디자인에 맞게 레이아웃 수정
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/5efe639d-b3cc-49df-85de-426653ef96a9" width="250px"> |

폴더 편집, 클립 편집, 클립 상세 화면 제약조건 수정

---

Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift

close #320 
- 모달 비율 수정
- 타이틀 수정

폴더 선택 모달 높이 비율 수정 및 클립 상세 화면 타이틀 수정

---

Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
Clipster/Clipster/Presentation/Scene/Common/View/MemoView.swift

메모 터치 안되는 이슈 수정

---

Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift

close #333
- 폴더 선택이 한번만 되는 문제 해결

폴더 선택 뷰 한번만 클릭되는 문제 수정

---

Clipster/Clipster.xcodeproj/project.pbxproj
Clipster/Clipster.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

close #344
- 사용되지 않는 Alamofire 패키지 제거
- VM 리팩터링을 위한 ReactorKit 패키지 추가

Package Dependency 변경

---

Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift

close #359 
URL 수정 시 Unread 상태로 변경
https://github.com/user-attachments/assets/97efdca5-c4b5-45ad-8262-42b8abe564e9

URL 수정 시 Unread 상태로 변경

---

Clipster/Clipster/Presentation/Resource/Icon.xcassets/XGray.imageset/Contents.json
Clipster/Clipster/Presentation/Resource/Icon.xcassets/XGray.imageset/XGray.svg
Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
Clipster/Clipster/Presentation/Scene/Common/TextField/CommonTextField.swift
Clipster/Clipster/Presentation/Scene/Common/View/SelectedFolderView.swift
Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
Clipster/Clipster/Presentation/Scene/EditFolder/ViewModel/EditFolderViewModel.swift

close #364 
1. 폴더 제목 10자 제한 label 제거
2. 폴더 제목 내부적으로 100자 제한
3. 폴더 제목과 URL clear button 추가
https://github.com/user-attachments/assets/bf9dd614-4882-4bdf-80f6-ddcf7896226d
https://github.com/user-attachments/assets/6a6e0201-cb62-4c3c-8dd2-af5adb5f37e6

TextField 수정 사항 반영

---

Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift

close #370 
내비게이션 바의 높이가 디자인과 상이하여 디자인에 맞춰 수정

내비게이션 바 높이 디자인에 맞게 수정

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/Data/DTO/ParsedURLMetadataDTO.swift
Clipster/Clipster/Data/Repository/URL/DefaultURLRepository.swift
Clipster/Clipster/Domain/Model/ParsedURLMetadata.swift
Clipster/Clipster/Domain/Protocol/Repository/URL/URLRepository.swift
Clipster/Clipster/Domain/Protocol/UseCase/URL/ParseURLUseCase.swift
Clipster/Clipster/Domain/UseCase/URL/DefaultParseURLUseCase.swift
Clipster/Clipster/Presentation/Model/URLMetadataDisplay.swift
Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift
Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift

close #293 
close #350 
- 특정 URL 적합성 통과 안 되는 이슈 해결
- 특정 URL og 태그 추출 안 되는 이슈 해결
- DIContainer 수정
- ParsedURLMetadata(+Display) - 스크린샷 이미지(Data) 프로퍼티 추가
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/56533126-036f-4cf8-9b77-9a7ea6c9cd66" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/03c1dee1-b3c0-43bf-98fa-41e28f49b3d1" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/5f302812-9562-4853-b5ac-1e12a1a6f078" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/57087dd7-84d8-4d67-9dd3-80fb9ef81bf8" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/4899883a-510b …

URLSession -> WebKit 마이그레이션

---

Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift

close #388
- 저장 시 updateAt을 현재 시간으로 수정하였습니다.

EditClip updateAt 조건 수정

---

Clipster/Clipster/App/Coordinator/App/AppCoordinator.swift
Clipster/Clipster/App/Coordinator/Protocol/Coordinator.swift
Clipster/Clipster/App/Source/SceneDelegate.swift
Clipster/Clipster/Presentation/Coordinator/Home/HomeCoordinator.swift
Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift

close #349 
- App, Home Coordinator 구현 및 적용
- 화면 전환이 잘되는지 확인을 하긴 했지만 혹시 모르니 맡은 화면에서 화면 전환이 잘 이루어지는지 확인부탁드립니다.

Coordinator 적용

---

Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift

close #420 
클립 추가 시 텍스트 필드로 포커스 이동
https://github.com/user-attachments/assets/91e4b212-7f81-49eb-a978-49c60c6ef81f

클립 추가 시 first responder 적용

---

Clipster/ClipsterTests/Domain/UseCase/Folder/CanSaveFolderUseCaseTests.swift

close #443 
폴더 저장 가능 여부 판단 로직 테스트 코드 추가

CanSaveFolderUseCase 테스트 코드 추가

---

Clipster/Clipster/Domain/UseCase/URL/DefaultParseURLUseCase.swift

close #439 
- http: 또는 https: 까지는 입력되어 있어야 웹 브라우저에도 인식되는 점을 감안하여 예외처리
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/08f01d63-12d3-469e-9962-986c14537ee0" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/b6455705-5df6-43aa-9fc6-96d625976b74" width="250px"> |

URL Prefix 예외처리

---

Clipster/Clipster/Data/Repository/URL/DefaultURLRepository.swift

close #474 
- 기존 PNG로 저장하던 방식에서 용량이 비대한 문제를 jpeg 압축을 통해 이미지 용량 줄이기

jpeg 압축 적용

---

Clipster/ClipsterTests/Domain/UseCase/Folder/FindFolderPathUseCaseTests.swift

close #449 
폴더 경로 계산 로직 테스트 코드 추가
Repository 테스트 코드 추가 시 리팩토링 예정

FindFolderPathUseCase 테스트 코드 추가

---

Clipster/ClipsterTests/Domain/UseCase/Folder/SanitizeFolderTitleUseCaseTests.swift

close #452 
폴더 제목 100글자 제한 로직 테스트 코드 추가

SanitizeFolderTitleUseCase 테스트 코드 추가

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift
Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
Clipster/Clipster/Presentation/Scene/UnvisitedClipList/Reactor/UnvisitedClipListReactor.swift
Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift

close #437 
- Reactor 구조 좀 더 선언형으로 리팩토링
- 에러를 던지지 않을때만 phase success 설정

UnvisitedClipListReactor 좀 더 선언형으로 리팩토링

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/Presentation/Model/HomeDisplay.swift
Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift
Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift

close #463 
- 홈화면 클립 섹션 추가
- 섹션 추가에 따른 Reactor 로직 추가

홈화면에 클립 섹션 추가

---

Clipster/Clipster/Data/Model/Persistence/Clipster.xcdatamodeld/Clipster3.xcdatamodel/contents
Clipster/Clipster/Data/Util/Mapper/DomainMapper.swift
Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift

close #527 
- EditClipView 홈 경로에도 클립 저장될 수 있도록 수정
- folder id 옵셔널 수정사항 반영 - Struct, CoreData

홈에 클립 저장 가능하도록 변경

---

Clipster/Clipster/Presentation/Scene/ClipDetail/Reactor/ClipDetailReactor.swift
Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift

close #539
- 클립 상세 화면에서 홈 보이도록 수정
- 클립 수정 시 화면 갱신 수정
https://github.com/user-attachments/assets/a1bb216b-e7b2-4d0f-90e3-c817332e0558

클립 상세 화면에서 홈 보이도록 수정

---

Clipster/ClipsterTests/Presentation/Mock/UseCase/Clip/MockFetchTopLevelClipsUseCase.swift
Clipster/ClipsterTests/Presentation/Reactor/HomeReactorTests.swift

close #543 
- 클립 섹션 추가 테스트 코드 대응

테스트 코드 클립 섹션 추가 대응

---

Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift
Clipster/Clipster/Data/Repository/Folder/DefaultFolderRepository.swift

close #547 
Repository가 cache를 optional로 가지도록 변경(ShareExtension에서 사용하기 위함)

Repository가 cache를 optional로 가지도록 변경

---

Clipster/Clipster/Presentation/Model/ClipDisplay.swift
Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift

close #542 
클립 상세화면에 날짜 정보 추가
- 최근 방문 날짜
- 최근 수정 날짜
- 생성 날자
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/595c6524-6111-4a04-b5b9-f07f8b7ea8da" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/34d0b971-e1ad-4c9e-873b-9a10bd89b18f" width="250px"> |

클립 상세화면 날짜 추가

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/App/Source/SceneDelegate.swift

close #568 
SceneDelegate에서 UserDefaults 갖도록 수정

SceneDelegate에서 UserDefaults 갖도록 수정

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/Domain/Protocol/UseCase/Query/DeleteAllRecentQueriesUseCase.swift
Clipster/Clipster/Domain/Protocol/UseCase/Query/DeleteRecentQueryUseCase.swift
Clipster/Clipster/Domain/Protocol/UseCase/Query/FetchRecentQueriesUseCase.swift
Clipster/Clipster/Domain/Protocol/UseCase/Query/SaveRecentQueryUseCase.swift
Clipster/Clipster/Domain/UseCase/Query/DefaultDeleteAllRecentQueriesUseCase.swift
Clipster/Clipster/Domain/UseCase/Query/DefaultDeleteRecentQueryUseCase.swift
Clipster/Clipster/Domain/UseCase/Query/DefaultFetchRecentQueriesUseCase.swift
Clipster/Clipster/Domain/UseCase/Query/DefaultSaveRecentQueryUseCase.swift

최근 검색어 UseCase 구현

---

Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
Clipster/Clipster/Data/Persistence/DefaultFolderStorage.swift
Clipster/Clipster/Data/Protocol/Persistence/ClipStorage.swift
Clipster/Clipster/Data/Protocol/Persistence/FolderStorage.swift
Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift
Clipster/Clipster/Data/Repository/Folder/DefaultFolderRepository.swift
Clipster/Clipster/Domain/Protocol/Repository/Clip/ClipRepository.swift
Clipster/Clipster/Domain/Protocol/Repository/Folder/FolderRepository.swift
Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchAllClipsUseCase.swift
Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchAllFoldersUseCase.swift

전체 폴더 및 클립 조회 구현

---

Clipster/Clipster.xcodeproj/project.pbxproj

close #599 
User, UserDTO 타겟 멤버십 수정

User, UserDTO 타겟 멤버십 수정

---

Clipster/ClipsterTests/Domain/UseCase/Folder/FilterSubfoldersUseCaseTests.swift
Clipster/ClipsterTests/Domain/UseCase/Folder/FindFolderPathUseCaseTests.swift

close #575 
UseCase 테스트 코드 목 데이터 사용하도록 수정

UseCase 테스트 코드 목 데이터 사용하도록 수정

---

Clipster/Clipster/Presentation/Scene/Common/Button/ConfirmButton.swift
Clipster/Clipster/Presentation/Scene/Common/Button/SaveButton.swift
Clipster/Clipster/Presentation/Scene/Common/Button/SelectButton.swift
Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift
Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift
Clipster/Clipster/Presentation/Scene/MyPage/Model/Item/MyPageItem.swift

close #603 
Blue400 색상을 Blue600으로 변경

Blue400 색상을 Blue600으로 변경

---

Clipster/Clipster/Presentation/Scene/FolderSelector/Reactor/FolderSelectorReactor.swift
Clipster/ClipsterTests/Presentation/Mock/UseCase/Folder/MockFetchSavePathLayoutOptionUseCase.swift
Clipster/ClipsterTests/Presentation/Mock/UseCase/Folder/MockFilterSubfoldersUseCase.swift
Clipster/ClipsterTests/Presentation/Mock/UseCase/Folder/MockFindFolderPathUseCase.swift
Clipster/ClipsterTests/Presentation/Reactor/FolderSelectorReactorTests.swift

close #441 
FolderSelector 테스트 추가

FolderSelector 테스트 추가

---

Clipster/ClipsterTests/Domain/UseCase/Clip/SearchClipsUseCaseTests.swift

close #589 
SearchClipsUseCase 테스트 추가

SearchClipsUseCase 테스트 추가

---

Clipster/ClipsterTests/Domain/UseCase/Folder/SortFoldersUseCaseTests.swift

close #590 
SortFoldersUseCase 테스트 추가

SortFoldersUseCase 테스트 추가

---

Clipster/ClipsterTests/Domain/UseCase/Clip/SortClipsUseCaseTests.swift
Clipster/ClipsterTests/Presentation/Mock/Entity/MockClip.swift

close #591 
SortClipsUseCase 테스트 추가

SortClipsUseCase 테스트 추가

---

Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchRecentVisitedClipsUseCase.swift

close #610 
최근 방문 클립을 가져올 때 정렬하도록 수정

최근 방문 클립을 가져올 때 정렬하도록 수정

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/Domain/UseCase/Setting/DefaultFetchClipSortOptionUseCase.swift
Clipster/Clipster/Domain/UseCase/Setting/DefaultFetchFolderSortOptionUseCase.swift
Clipster/Clipster/Domain/UseCase/Setting/DefaultFetchSavePathLayoutOptionUseCase.swift
Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift

close #621 
close #606 
- 폴더/클립 정렬, 저장 경로 기본값 수정
- 홈화면 폴더/클립 정렬 적용

정렬 기본값 수정 및 홈화면 정렬 적용

---

Clipster/Clipster/App/DIContainer/DIContainer.swift
Clipster/Clipster/Presentation/Coordinator/MyPage/MyPageCoordinator.swift
Clipster/Clipster/Presentation/Scene/EditNickname/SubView/View/EditNicknameView.swift
Clipster/Clipster/Presentation/Scene/EditNickname/ViewController/EditNicknameViewController.swift
Clipster/Clipster/Presentation/Scene/MyPage/Model/Item/MyPageSection.swift
Clipster/Clipster/Presentation/Scene/MyPage/Reactor/MyPageReactor.swift
Clipster/Clipster/Presentation/Scene/MyPage/SubView/View/MyPageView.swift
Clipster/Clipster/Presentation/Scene/MyPage/ViewController/MyPageViewController.swift

close #601 
- MyPageReactor 로그인, 로그인 여부, 닉네임 불러오기 구현
- 닉네임 변경 모달 구현
- 휴지통 섹션 제거
- 섹션 그룹 높이 경고 해결
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/85474a54-68c1-4749-8e7a-bea5d056db04" width="250px"> |

마이페이지 화면 로그인 기능 적용 및 닉네임 변경 모달 구현

---

Clipster/Clipster/Presentation/Scene/MyPage/Reactor/MyPageReactor.swift

close #637 
- 마이페이지 섹션 로그인 기능 보류 대응
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/c064026e-731d-4750-9cd6-894b3a109482" width="250px"> |

마이페이지 섹션 로그인 기능 보류 대응

---

Clipster/ShareExtension/ViewController/ShareViewController.swift

close #646 
- 네비게이션 안 보이는 문제 수정
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/f38436cf-4e11-4463-b661-3cdec342c5e6" width="250px"> |

Share Extension 네비게이션 안 보이는 문제 수정

---

Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
Clipster/Clipster/Data/Persistence/DefaultFolderStorage.swift
Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchFolderUseCase.swift
Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchTopLevelFoldersUseCase.swift

close #648
- 재귀적으로 soft-delete를 필터링하도록 로직 수정
- 재귀 메서드들의 코드 컨벤션 통일

삭제된 항목을 item count에 포함시키는 이슈 수정

---

Clipster/Clipster.xcodeproj/project.pbxproj
Clipster/Clipster/Presentation/Model/ParseResultType.swift
Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
Clipster/ShareExtension/Reactor/ShareReactor.swift

close #661 
- reduce 내에 산발적인 State 변경으로 낮은 응집도와 높은 복잡성을 개선하기 위해 State 내에 일부를 Derived State 개념을 도입하여 연산 프로퍼티로 활용

EditClipReactor Derived State 도입 리팩토링

---

Clipster/Clipster.xcodeproj/project.pbxproj
Clipster/ShareExtension/Reactor/ShareReactor.swift

close #680
ClipValidType -> ParseResultType 변경으로 인한 문제 수정

TargetMembership 수정

---

Clipster/Clipster/Presentation/Scene/Folder/Reactor/FolderReactor.swift

close #679
FolderReactor에 Derived State 적용
FolderReactorTests에는 코드 수정이 불필요하다고 판단하여 수정하지 않았습니다.

FolderReactor에 Derived State 적용

---

Clipster/ClipsterTests/Presentation/Mock/UseCase/ShareExtension/MockExtractExtensionContextUseCase.swift
Clipster/ClipsterTests/Presentation/Reactor/ShareReactorTests.swift
Clipster/ShareExtension/Reactor/ShareReactor.swift
Clipster/ShareExtension/ViewController/ShareViewController.swift

close #667 
- 네이밍 수정
테스트 요소
action에 의해 정상적으로 State 변경이 되는지
action에 의해 변경되는 State(핵심 소스), 핵심 소스에 의해 변경되는 Dervied Stat
머지 타겟 브랜치가 #658 로 되어 있으니 PR 676부터 검수해 주시면 감사하겠습니다.

ShareReactor 테스트
