TeamSaltshaker/DamDam

Clipster/Clipster/Presentation/Scene/EditFolder/Subview/Button/EditFolderBackButton.swift, Clipster/Clipster/Presentation/Scene/EditFolder/Subview/Button/EditFolderSaveButton.swift, Clipster/Clipster/Presentation/Scene/EditFolder/Subview/TextField/EditFolderTextField.swift, Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift, Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
close #7 
- Back Button
- Save Button
- TextField
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/4a70a698-a68f-4de7-99cd-9bfd59733862" width="250px"> |
- base가 `feat/#8-edit-folder-vm` 브랜치인 것은 병합되지 않은 커밋(ViewModel 관련)이 PR에 잡히지 않게 하기 위함입니다.
리뷰 후에는 `dev` 브랜치로 병합할 예정입니다.
- 타이틀이 비어있는 이유는 현재 기획상 이전 화면의 이름(상위 폴더 이름인 것 같습니다.)을 사용하는 것으로 되어 있어서,
화면 전환 시 전달 받는 것으로 설계했기 때문입니다.
- 내비게이션 버튼들의 위치가 현재는 공통 뷰가 아닌 EditFolder의 커스텀 뷰로 되어 있는데요.
우선은 제 생각대로 작업을 진행했기 때문에, 공통으로 빼지 않았습니다.
다른 분들이 더 좋은 방법으로 구현하실 수도 있을 것 같아서, 협의 후에 수정하도록 하겠습니다.
=> [Feat] EditFolder UI 구현

Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift, Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/ViewModel.swift
close #49 
UI Component 추가 및 접근 제어자 수정 등을 ViewModel PR로 포함한 점은 이전 EditClipView에 작성해야할 부분이지만 당시에 생각 못 했고, 그것만 따로 분리하기엔 애매해서 포함 했습니다. 양해 부탁드립니다.
=> [Feat] EditClipViewModel 구현

Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
close #50 
| 실행 기기 | 스크린샷(또는 GIF) | 설명 |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/0aebd340-36c1-4a7c-a14f-e2656ac3df0e"  width="250px"> | 클립 생성 버튼 누를 때? |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/7a0268c8-5674-406a-aaa3-10526a7914a7"  width="250px"> | Share Extension 또는 Toast Viewd에서 Push 또는 ClipDetailView에서 Push |
Share Extension과 Toast View에서 EditClipView로 Push 되는 경우는 URL만 입력되어 Push되기 때문에 디폴트 파라미터로 구현
```
init(urlText: String = "", memoText: String = "") { }
```
=> [Feat] EditClipView 바인딩

Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/Button/ClipDetailBackButton.swift, Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
close #24 
View <-> ViewModel 바인딩
임시로 클립 상세 화면용 버튼을 구성하였습니다.
디자인이 확정되면, 공통으로 분리할 예정입니다.
=> [Feat] ClipDetail UI 바인딩

Clipster/Clipster/Data/DTO/ParsedURLMetadataDTO.swift, Clipster/Clipster/Data/Repository/URLMetadata/DefaultURLMetadataRepository.swift, Clipster/Clipster/Domain/Entity/ParsedURLMetadata.swift, Clipster/Clipster/Domain/Protocol/Repository/URLMetadata/URLMetadataRepository.swift, Clipster/Clipster/Domain/Protocol/UseCase/URLMetadata/ParseURLMetadataUseCase.swift, Clipster/Clipster/Domain/UseCase/URLMetadata/DefaultParseURLMetadataUseCase.swift, Clipster/Clipster/Presentation/Model/URLMetadataDisplay.swift
close #58 
- URLMetadata 파싱 로직 구현
- URLMetadataDisplay에서 thumbnailImageURL 타입 변경
종종 og: image가 없는 경우도 있어 thumbnailImageURL을 옵셔널 타입으로 수정하였습니다.
```swift
ParsedURLMetadataDTO(
...
thumbnailImage: extractMetaContent(html: html, property: "og:image") ?? ""
)
```
=> [Feat] URLMetadata 파싱 구현

Clipster/Clipster/App/Source/SceneDelegate.swift, Clipster/Clipster/Domain/Protocol/UseCase/Clip/DeleteClipUseCase.swift, Clipster/Clipster/Domain/Protocol/UseCase/Folder/DeleteFolderUseCase.swift, Clipster/Clipster/Domain/Protocol/UseCase/Folder/FetchTopLevelFoldersUseCase.swift, Clipster/Clipster/Domain/UseCase/Clip/DefaultDeleteClipUseCase.swift, Clipster/Clipster/Domain/UseCase/Folder/DefaultDeleteFolderUseCase.swift, Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchTopLevelFoldersUseCase.swift, Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift, Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift, Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
close #59 
- 화면이동을 담당할 Route 열거형 추가
- 각 Action에 맞는 로직 추가
- DeleteUseCase 추가 및 수정
| 클립 관련 액션 | <img src="https://github.com/user-attachments/assets/cab9ebd8-a6ab-486f-a506-1cd98a6cb3db" width="500px"> |
| 폴더 및 라이센스 관련 액션 | <img src="https://github.com/user-attachments/assets/78150bd5-9090-4f02-88b1-634598cb931d" width="500px"> |
- 화면이동을 위해 Route도 기존의 Action, State와 동일하게 열거형으로 생성(추후 합의)
- 각 화면이동에 필요한 데이터 타입이 적절한지
- VM에서 action을 수신했을 때의 Logging은 다음 PR때 추가하겠습니다.
- 병합되지 않은 커밋이 PR에 잡히지 않게 하기 위하여 base를 이전 브랜치로 지정했습니다. 이전 브랜치 병합 후 수정하겠습니다.
=> [Feat] HomeViewModel Action, State, Route 바인딩

Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift, Clipster/Clipster/Presentation/Scene/EditClip/Subview/StackView/URLValidationStackView.swift, Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift, Clipster/Clipster/Presentation/Util/Extension/ViewController+Extension.swift
close #83 
- 저장 버튼 활성화 여부 바인딩
- URLMetadata 파싱 관련 로직 적용
- URLMetadataStackView, URLValidationStackView 애니메이션 추가
- 키보드 내리기 Extension 추가
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/c610c3a2-9da9-42a3-b676-b2c4e0e5dc5e" width="250px"> |
키보드 내리기 Extension 작성과 함께 적용하였기 때문에 현재 PR에 포함하여 올렸습니다.
=> [Feat] EditClipView UI 바인딩

Clipster/Clipster/Presentation/Scene/Common/Cell/SectionHeaderView.swift, Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift, Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift, Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift, Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
close #92 
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/ad6b78f2-7a30-43bb-a7c8-99bddf614c3e" width="250px"> |
- 라이센스 버튼 제거
- 읽지 않은 클립 뷰로 이동하기 위한 버튼을 추가
- 버튼 탭 시 화면 이동
- 기본값으로 Hidden 처리 및 setShowAllButtonVisible 메소드를 통해 필요할때만 보여지도록 구현
=> [Feat] Section Header View 전체보기 버튼 추가 및 바인딩

Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
close #90
- 이니셜라이저 추가
| 실행 기기 | 스크린샷(또는 GIF) | 케이스 |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/9b0507c8-d506-4416-a85a-4c3b290b06c6" width="250px"> | 클립 수정 버튼으로 진입 |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/b112aa6a-b270-4cb1-a376-1e3a253b110b" width="250px"> | Share Extension 또는 토스트 뷰로 진입 |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/2cc437bc-25ff-4607-a7b7-a372ca3d22ea" width="250px"> | 클립 생성 버튼으로 진입 |
=> [Feat] 클립 수정 버튼으로 EditClipView 진입 가능하도록 수정

Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift, Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift, Clipster/Clipster/Presentation/Scene/Folder/ViewModel/FolderViewModel.swift
close #73 
- FolderView UI 구현
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/03a09cb5-8429-45b9-b7c1-353b21419556" width="250px"> |
- trailing swipe 구현은 다음 PR에서 진행하겠습니다
- ui 수정이 예정돼있어서 해당 PR에서 디테일하게 구현은 안했습니다(폰트, 간격, 색상 등)
- NavigationBar에 공통 컴포넌트 구현 사항을 반영해야하는 상태입니다
=> [Feat] FolderView UI 구현

Clipster/Clipster/Presentation/Scene/Common/Button/BackButton.swift, Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift, Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift, Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift, Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift, Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewModel/UnvisitedClipListViewModel.swift
close #136 
- 홈 뷰 네비게이션 뷰 적용
- 방문하지 않은 클립 뷰 네비게이션 뷰 적용
- 홈 뷰에서 네비게이션 바 Hidden
- BackButton Configure 호출 추가
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/53742b7e-e96b-4fe8-9010-01e628ab4843" width="250px"> |
=> [Feat] 홈 뷰, 방문하지 않은 클립 뷰 네비게이션 뷰 적용

Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift
close #158 
- 방문하지 않은 클립 뷰 테이블뷰로 변경
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/418dd496-57a5-423e-b72a-7e159d6e60ed" width="250px"> |
세부적인 UI는 피그마 동기화 하면서 한번에 하겠습니다.
=> [Refactor] 방문하지 않은 클립 뷰 테이블뷰로 변경

Clipster/Clipster/App/DIContainer/DIContainer.swift, Clipster/Clipster/Domain/Protocol/UseCase/Clip/CreateClipUseCase.swift, Clipster/Clipster/Domain/Protocol/UseCase/Clip/UpdateClipUseCase.swift, Clipster/Clipster/Domain/UseCase/Clip/DefaultCreateClipUseCase.swift, Clipster/Clipster/Domain/UseCase/Clip/DefaultUpdateClipUseCase.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
close #89 
- Clip Create/Update UseCase & Repository 구현
- VIewModel 및 DIContainer 수정
- 클립 저장/수정 구현
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/3733efeb-ea7a-4434-a040-6b09c337315b" width="250px"> |
현재 인지하고 있는 예외처리 사항에 대해 다음 PR에 구현 예정
- 폴더 없을 때 EmptyView
- 클립 편집 버튼으로 EditClipVIew 진입 시 저장된 내용과 현재 기록된 내용 비교하여 저장 버튼 활성화 여부 결정
- Share Extension으로 EditClipView 진입 시 홈(최상위)에 생성된 폴더 중 아무거나 가져오기
=> EditClipView 저장/수정 버튼 로직 구현

Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
close #200 
홈 선택 시 이후에도 지속적으로 폴더 변경이 가능하게 하기 위함
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/d0c3eedd-c68b-4b8c-8966-f3219600a91e" width="250px"> |
=> 홈 선택시 폴더 선택 화면 보이게 수정

Clipster/Clipster/App/DIContainer/DIContainer.swift, Clipster/Clipster/Presentation/Scene/Common/Button/AddButton.swift, Clipster/Clipster/Presentation/Scene/Common/Button/BackButton.swift, Clipster/Clipster/Presentation/Scene/Common/Cell/ClipCell.swift, Clipster/Clipster/Presentation/Scene/Common/Cell/FolderCell.swift, Clipster/Clipster/Presentation/Scene/Common/Cell/TableHeaderView.swift, Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift, Clipster/Clipster/Presentation/Scene/Common/View/EmptyView.swift, Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift, Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift, Clipster/Clipster/Presentation/Scene/Folder/ViewModel/FolderViewModel.swift
close #151 
- FolderView에 폰트, 아이콘, 컬러 지정
- FullSwipe가 가능하도록 UX 변경
- FolderView 및 관련된 공통 View의 UI 변경
- 데이터가 없는 섹션의 경우 헤더도 출력하지 않도록 변경
- Action이 진행된 이후 데이터 reload 구현
- 데이터가 없을 경우 EmptyView 표시
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/4c26afdc-daac-48e9-b82e-902a1eead349" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/c003e4c7-db31-4458-aefb-c11662c5e465" width="250px"> |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/c8fd6700-ecde-4dc7-80df-3ae67f958f1d" width="250px"> |
EmptyView의 Constraint가 수정된 부분이 있습니다.
=> FolderView UI/UX 상세 구현

Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift, Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift, Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift, Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift, Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift, Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift, Clipster/Clipster/Presentation/Util/Extension/ViewController+Extension.swift
close #210 
- 방문하지 않은 클립 뷰 ListConfiguration으로 리팩터링
- DeleteAlert 확장으로 재사용
- 폴더뷰, 방문하지 않은 클립 뷰 Alert 적용
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/d46a3a6c-6368-4b75-ae92-06c67d736adf" width="250px"> |
=> 방문하지 않은 클립 뷰 리팩토링 및 Alert 추가

Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift, Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
close #215 
내비게이션 타이틀 길이보다 텍스트가 길어질 경우 말줄임표 처리
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/2862016e-6dc2-446e-87f2-0ab378191b1f" width="250px"> |
=> 내비게이션 타이틀 길이 제한

Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/CollectionHeaderView.swift, Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
close #231 
- 헤더뷰가 재사용되면서 중복 바인딩이 되어 이벤트가 중복 발생
- 재사용 시점마다 구독을 초기화하여 해결
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/5e6b8028-3005-46f1-b438-c3d41bc55189" width="250px"> |
=> 헤더뷰 재사용으로 인한 중복 바인딩 해결

Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift, Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift, Clipster/Clipster/Presentation/Scene/Folder/ViewModel/FolderViewModel.swift
close #236 
- FolderView -> 클립 추가 시 폴더 파라미터 전달
- EditClipView init Type 예외처리 수정
=> 폴더 뷰에서 클립 추가 시 최근 수정된 폴더로 보이는 문제 해결

Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift, Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift, Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift, Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
close #225
화면 왼쪽에서 안쪽으로 스와이프할 때, VC가 pop되는 기능을 활성화 했습니다(InteractivePopGesture 활성화)
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/1b6e9770-8a4c-4471-9dc9-11e8f95cbf6a" width="250px"> |
```swift
extension EditFolderViewController: UIGestureRecognizerDelegate {
func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
true
}
}
```
이렇게 다 안쓰고, 그냥 Delegate를 채택하기만 해도 원하는 대로 동작은 하는 것 같습니다.
```swift
extension EditFolderViewController: UIGestureRecognizerDelegate {}
```
근데 나중에 왜 추가했는지 못알아볼 것 같아서 그냥 명시적으로 메서드 작성했습니다.
=> InteractivePopGesture 활성화

Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift, Clipster/Clipster/Presentation/Scene/EditFolder/ViewModel/EditFolderViewModel.swift, Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift, Clipster/Clipster/Presentation/Scene/FolderSelector/ViewModel/FolderSelectorViewModel.swift
close #229 
클립 추가/편집 화면 -> 폴더 선택 화면에서 홈 선택 비활성화
https://github.com/user-attachments/assets/5fbf6030-d3c1-4c3e-a0a7-cd6021d22be5
=> 클립 추가/편집 화면에서 폴더 선택 시 홈이 선택되는 버그 수정

Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
close #232
close #238
폴더 화면에서 단일 섹션일 때, 테이블 뷰의 여백이 어색한 점을 수정했습니다.
https://github.com/user-attachments/assets/ff189175-4a31-4a55-9e57-6229e35e1175
=> 폴더 화면 단일 섹션일 때 여백 조정

Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift, Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
- close #266 
- close #271 
- 폴더 섹션 TopPadding 기본값으로 인하여 여백 증가 -> 0으로 설정
- 헤더 높이 48로 변경
- EmptyView 초기 Hidden 처리
- Cell CornerRadius self로 변경
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/786bb703-435b-4da6-a576-62c61bf820cf" width="250px"> |
=> 홈 폴더 섹션만 있을경우 위쪽 여백 다름 해결 및 기타 수정

Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift, Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift, Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift, Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
close #283 
- 다른 화면으로 이동할때마다 delegate가 변경되어 pop이후 제스처가 안되는 현상
- 해결하기 위해 viewWillAppear에서 delegate 설정
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/5eaa58e3-8960-49b6-841e-c2110251b835" width="250px"> |
=> InteractivePopGesture 연달아 pop 안됨 해결

Clipster/Clipster/Domain/UseCase/URLValidation/DefaultCheckVaildityUseCase.swift, Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
close #273 
- [] 새로운 기능 추가
- xcode CUICatalog 관련 경고 메시지 수정
- 폴더 항목 개수 표시 형식 수정
- 폴더 재선택 안 되는 문제 수정
=> EditClipView 폴더 재선택 안 되는 이슈 해결

Clipster/Clipster/App/Derived/Info.plist, Clipster/Clipster/App/Source/SceneDelegate.swift, Clipster/ShareExtension/ShareViewController.swift
close #287 
Debug와 Release Bundle Identifier 구분에 따라 같이 수정됐어야 하는 부분들을 수정했습니다.
기존 단일 URL Scheme이였던 `clipster://`를 `damdamdebug://`와 `damdam://`으로 변경했습니다.
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/3c805fa3-4c81-4ca5-a142-9c863aedabfa" width="250px"> |
=> URL Scheme 구분하여 Share Extension 이슈 해결

Clipster/Clipster/Presentation/Scene/Common/View/MemoView.swift
close #298 
피그마대로 높이 수정
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/0cef4aaa-bf6b-4f32-8963-12a5914f9582" width="250px"> |
=> 메모 텍스트뷰 높이 수정

Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
close #305 
- 저장 버튼 활성화 여부 수정
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/21ba923a-8a53-469f-a6fe-088c6e9416d3" width="250px"> |
메모 입력하지 않아도 저장 가능
=> 저장 버튼 활성화 여부 수정

Clipster/Clipster/Presentation/Scene/Common/Cell/FolderListCell.swift
close #295 
- top(24) + size(48) + bottom(24) = 72 를 기대하지만 UIkit에서 내부적으로 계산한 높이는 72와 다를수 있음
- 이로인해 충돌이 발생한 것으로 추정
- 이를 해결하기 위해 우선순위를 낮춤으로써 UIkit에서 계산한 높이를 사용할 수 있도록 수정
=> FolderListCell 오토레이아웃 경고 해결

Clipster/Clipster/Data/Util/Mapper/DomainMapper.swift
close #264 
ThumbnailImageURL이 nil값이 허용되도록 기획이 수정되었는데, DomainMapper에서는 이를 허용하지 않아서 클립이 추가되지 않은 것처럼 보이는 이슈가 있었습니다. nil이여도 URLMetadata를 init하는데 실패하지 않도록 수정했습니다.
https://github.com/user-attachments/assets/c8ae9de6-dfa2-4d13-a1b2-3988ec9ae311
일단 추가는 되는데, 셀 표시가 정상적으로 되지는 않습니다. 이슈로 추가하겠습니다.
=> 썸네일이 없어도 오류로 처리하지 않도록 수정

Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift, Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
- close #330 
- 화면 이동시 throttle처리를 통한 중복 push 방지
=> 홈, 방문하지 않은 클립 화면 push 한번만 일어나도록 수정

Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
close #379 
close #391 
섹션 별 높이 48로 고정 및 8 여백 동일하게 수정
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/264c21b3-6088-4736-9ef4-725d73de67c3" width="500px"> |
=> 홈화면 섹션별 높이 같도록 수정

Clipster/Clipster/Data/Model/Clipster.xcdatamodeld/.xccurrentversion, Clipster/Clipster/Data/Model/Clipster.xcdatamodeld/Clipster2.xcdatamodel/contents, Clipster/Clipster/Data/Model/URLMetadataEntity.swift, Clipster/Clipster/Data/Persistence/CoreDataStack.swift, Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift, Clipster/Clipster/Data/Util/Mapper/DomainMapper.swift, Clipster/Clipster/Domain/Model/URLMetadata.swift, Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
close #404
- CoreData DataModel 버전 추가
- URLMetadataEntity에 screenshotData 속성 추가(lightweight migration)
- Domain Layer의 URLMetadata에 screenshotData 속성 추가
- 스키마 변경에 따른 연계된 메서드들의 호출 수정
=> URLMetadataEntity에 screenshotData 속성 추가

Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
close #398 
- URL이 유효하고 선택된 폴더가 있을 경우에 저장 버튼이 활성화 되도록 수정
- 편집 또는 ShareExtension 시 전달 받은 URL 유효성 검사 수행되도록 수정
https://github.com/user-attachments/assets/7912bed8-cf16-455c-8422-51383e9e4f13
=> 클립 편집 화면 저장 버튼 활성화 관련 수정

Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift, Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
close #401 
폴더 편집 화면 전환 시 현재 폴더명이 보이도록 수정
=> 폴더 편집 시 텍스트 필드 비어있는 이슈 해결

Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift, Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift, Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift, Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift, Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
close #409 
- 스크린샷 적용하기
| 실행 기기 | 스크린샷(또는 GIF) | 비고 |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/8986acbf-d4be-4e4e-861a-83b08abc49b0" width="250px"> | HTML 썸네일 이미지(유튜브) |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/928eb839-c337-45ca-9040-d53e2035fdd7" width="250px"> | HTML 썸네일 이미지(유튜브) |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/c2ebf568-a339-4707-a55c-b9c2f787a5fa" width="250px"> | HTML 썸네일 이미지(유튜브) |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/30e893f1-0ef0-4fe2-9d49-620118a8e345" width="250px"> | HTML 썸네일 이미지(유튜브) |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/5bf6b8e6-a9df-4265-9307-8ee0f328c965" …
=> 스크린샷 이미지 적용

Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
close #413 
편집 화면 진입 시 전달된 URL에 대한 유효성 검사 진행하도록 수정
https://github.com/user-attachments/assets/80ba1ea5-7c1c-4922-8fd4-0aa6f75f1485
=> 클립 편집화면 진입 시 유효성 검사

Clipster/Clipster/Domain/UseCase/URL/DefaultParseURLUseCase.swift, Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift, Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift, Clipster/Clipster/Presentation/Scene/EditFolder/Reactor/EditFolderReactor.swift, Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
close #444 
- 스크롤 뷰 키보드 동적 레이아웃
| 실행 기기 | 스크린샷(또는 GIF) | 비고 |
| iPhone 16 Pro | <video src="https://github.com/user-attachments/assets/1d4738c7-95d8-40cc-8e7b-1d925b00ca1b" width="250px"> | 기존 문제가 생겼던 상황 |
| iPhone 16 Pro | <video src="https://github.com/user-attachments/assets/b5074cfe-8305-452a-a4a3-1d83c2879962" width="250px"> | 개선 이후 |
- ~viewDidLoad에서 동작했던 textField 포커싱(키보드 올리기)를 viewIsAppearing으로 하는 것이 더 적합하여 변경 했습니다.~
- 애니메이션이랑 헷갈렸네요 viewDidAppear로 수정하고 다시 푸시하겠습니다
- base 브랜치가 dev가 아니라 #478 부터 확인 부탁드립니다.
=> EditClipView 키보드 높이에 따른 동적 레이아웃 적용

Clipster/Clipster/App/DIContainer/DIContainer.swift, Clipster/Clipster/Domain/Protocol/UseCase/Clip/VisitClipUseCase.swift, Clipster/Clipster/Domain/UseCase/Clip/DefaultVisitClipUseCase.swift, Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift, Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
close #436 
- Reactor 구조 좀 더 선언형으로 리팩토링
- VisitClipUseCase 분리
```swift
.catch { .just(.setPhase(.error($0.localizedDescription))) },
.just(.setPhase(.success))
````
- fromAsync가 제네릭이라 함수 내부에서 .setPhase(.success)까지 함께 반환할 수 없어, 결국 외부에서 무조건 .just(.setPhase(.success))를 붙이게 되어 에러가 나도 성공처럼 보이는 구조가 조금 어색하긴합니다. (결과적으로는 문제가 있진 않음)
- 컨벤션대로 하긴 했지만, 솔직히 재사용성도 떨어지고 가독성도 낮아진거 같습니다.
- 개선점이 있다면 피드백 부탁 드립니다.
=> HomeReactor 좀 더 선언형으로 리팩토링

Clipster/Clipster/App/DIContainer/DIContainer.swift, Clipster/Clipster/Presentation/Scene/Folder/Reactor/FolderReactor.swift
close #508 
- 클립 방문 시, UpdateUseCase가 아닌 VisitUseCase를 사용하도록 변경
- 향후 Activity Indictor와 Error Alert 구현을 위한 Phase 속성 추가
- State를 직접 변경하지 않았기 때문에, 적절하지 않았던 delete mutation case 제거
- 위 변경에 따른 DIContainer 수정
FolderView에 ActivityIndicator와 ErrorAlert를 추가하는 작업은 별도 Task로 진행하겠습니다.
=> FolderReactor 리팩터링

Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift, Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift, Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift, Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift, Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift, Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift, Clipster/Clipster/Presentation/Util/Extension/UIViewController+Extension.swift
close #511 
- FolderReactor의 Phase 변경에 따른 ActivityIndicator와 ErrorAlert 구현
- ErrorAlert의 경우 UIViewController+Extension에 구현해서 재사용할 수 있도록 구현했습니다.
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/51da3cd5-53bd-4b6a-84c9-25b8227a41b3" width="250px"> |
https://github.com/user-attachments/assets/ccd8d556-8b26-40b6-9412-1301dad57bca
Error Alert를 독립적으로 구현한 다른 화면들에도 같이 적용했습니다.
수정된 화면: Folder, ClipDetail, EditFolder, Home, UnvisitedClipList
=> FolderView UI 개선

Clipster/Clipster/Data/Util/Mapper/DomainMapper.swift, Clipster/Clipster/Domain/Model/Entity/Clip.swift, Clipster/Clipster/Domain/Model/URLMetadata.swift, Clipster/Clipster/Domain/UseCase/Clip/DefaultDeleteClipUseCase.swift, Clipster/Clipster/Domain/UseCase/Clip/DefaultVisitClipUseCase.swift, Clipster/Clipster/Presentation/Model/URLMetadataDisplay.swift, Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift, Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift, Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
close #501 
- URLMetadataStackView / URLMetadataDisplay description 프로퍼티 추가
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/073aaba4-ac21-4e01-a300-e170f89fbba8" width="250px"> |
- 현재 UI는 EditClipView에서만 적용되고 있습니다.
- 추후에 CoreData에 Description이 포함된 이후에 다른 뷰(description을 포함한 클립이 생성된다면)에서도 UI 적용 가능할 것입니다.
=> Description UI 적용

Clipster/Clipster/App/DIContainer/DIContainer.swift, Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift, Clipster/Clipster/Data/Protocol/Persistence/ClipStorage.swift, Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift, Clipster/Clipster/Domain/Model/Entity/Clip.swift, Clipster/Clipster/Domain/Protocol/Repository/Clip/ClipRepository.swift, Clipster/Clipster/Domain/Protocol/UseCase/Clip/FetchTopLevelClipsUseCase.swift, Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchTopLevelClipsUseCase.swift, Clipster/Clipster/Presentation/Scene/ClipDetail/Reactor/ClipDetailReactor.swift, Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
close #495
- Clip 엔티티의 `folderID`를 옵셔널 타입으로 변경(옵셔널이면 TopLevel 클립이라는 뜻입니다)
- ClipStorage, ClipRepository, ClipUseCase에 `fetchTopLevelClips` 로직 구현
- insert, update 조건에서 folder nil check 로직 제거
- 위 변경 사항에 따른 빌드 오류 수정
- UI 구현은 미포함입니다.
- 빌드 오류는 수정되었으나, 논리적인 오류가 모두 수정된 상태는 아닙니다. (각 화면 담당자들한테 전달 완료 ✅)
=> 폴더 없이도 클립이 저장될 수 있도록 변경

Clipster/Clipster/App/Derived/Info.plist, Clipster/Clipster/Data/Repository/URL/DefaultURLRepository.swift, Clipster/Clipster/Domain/UseCase/URL/DefaultParseURLUseCase.swift, Clipster/ShareExtension/Info.plist, Clipster/ShareExtension/ShareViewController.swift
close #451 
- ATS 허용 - 원티드 앱에서 공고 공유 시 http:// URL 형식
- Share Extension URL 파싱 로직 수정
- 다양한 앱에서 공유 시 담담 앱 보이도록 수정
- 유튜브 앱, 깃허브 앱, 네이버 앱(검색 이후 공유 버튼), 네이버 카페 앱, 원티드 앱, 알바천국 앱에서 공유 버튼 클릭 시 담담 확인 했습니다.
- URL 메타데이터 추출 시 앱스토어는 현재 추출할 수 없습니다. URL 메타데이터 추출을 WKWebView로 진행하고 있는데, 보안상의 이유로 애플이 제공하는 앱의 대부분은 WKWebView로 접근하지 못 한다고 하네요. (저장 이후 웹 뷰로 이동은 됨)
- WKWebView를 사용하는 이유가 스크린 샷 때문인데 추후에 애플 관련 URL은 URLSession이나 Apple Search API 같은걸로 파싱해야겠네요.
- 타 앱에서 안 보이는 경우 제보 받습니다.
=> 다른 모든 앱에서 공유하기 버튼으로 담담 보이도록 수정

Clipster/Clipster/Presentation/Scene/Common/Cell/CollectionHeaderView.swift, Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift
close #535 
- 클립 삭제 후 Reload
- 섹션 헤더 재사용시 Hidden 처리
=> 홈 클립 삭제 후 Reload 및 섹션 헤더 재사용 Hidden 처리

Clipster/Clipster/App/DIContainer/DIContainer.swift, Clipster/Clipster/App/Source/SceneDelegate.swift, Clipster/Clipster/Data/Model/Cache/FolderClipCache.swift, Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift, Clipster/Clipster/Data/Repository/Folder/DefaultFolderRepository.swift, Clipster/Clipster/Domain/Error/DomainError.swift, Clipster/Clipster/Domain/Protocol/Repository/Clip/ClipRepository.swift, Clipster/Clipster/Domain/UseCase/Clip/DefaultCreateClipUseCase.swift
close #492 
- In-memory 캐시 초기 구현
LaunchScreen 직후 모든 데이터를 Fetch한 뒤, `isInitialized` 플래그를 true로 만드는 호출이 있어야 인메모리 캐싱이 본격적으로 의미를 갖는데, 아직 Launch 로직이 구현되어 있지 않습니다. 따라서 이 PR이 머지가 되더라도 캐싱이 되진 않으니 파일 구조와 로직의 구현 방식 위주로 봐주시면 감사하겠습니다 🙏
`FolderClipCache`라는 이름이 조금 아쉬운데, 더 나은 의견이 있다면 수정하겠습니다.
=> In-memory 캐시 초기 구현

Clipster/Clipster/App/DIContainer/DIContainer.swift, Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
close #577
- 더이상 ShareExtension에서 메인 앱 진입하지 않기 때문에 EditClipView 내의 Share Extension에서 진입할 경우에 대한 로직 제거
=> EditClipView - Share Extension 관련 로직 제거

Clipster/Clipster/Presentation/Scene/FolderSelector/Reactor/FolderSelectorReactor.swift
close #585 
폴더 선택화면에서 하위 폴더를 선택 후 상위 폴더를 접었을 때 타이틀이 '홈'으로 변경됨
폴더 선택 후 상위 폴더를 접어도 타이틀에 선택된 폴더 이름이 보이도록 수정
https://github.com/user-attachments/assets/3ac9a852-c0c4-4302-8930-b60885cf80b4
https://github.com/user-attachments/assets/2b79e18d-a108-4829-9fe6-de375cadb84e
=> 폴더 선택 후 상위 폴더를 접어도 타이틀에 선택된 폴더 이름이 보이도록 수정

Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift, Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
close #612
- EditClipView 진입 시 클립보드 URL을 감지합니다.
| 실행 기기 | 스크린샷(또는 GIF) | 비고 |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/dcdcd3ef-80b5-4d7e-8925-805630272a33" width="250px"> | 클립보드 복사 동의 |
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/a37834fc-80ea-42da-b343-07a7cd6c73ab" width="250px"> | 클립보드 복사 거절 |
동의 또는 거절을 누른 이후 EditClipView 진입 시에는 클립보드 복사 감지 안 됩니다.(키보드 올라옴)
=> EditClipView 진입 시 클립보드 감지

Clipster/Clipster/Presentation/Model/ClipDisplay.swift, Clipster/Clipster/Presentation/Scene/Common/Button/AddFAButton.swift, Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift, Clipster/Clipster/Presentation/Scene/Common/Cell/FolderListCell.swift, Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift, Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift, Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
close #615 
- ClipListCell Chevron 이미지 제거
- Clip SubTitle 있을경우 Cell에 보여주도록 수정
- FA 버튼 크기 변경
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/07ad618c-7baf-43e8-b01a-848255512670" width="250px"> |
=> 클립/폴더 셸 디자인 수정 사항 반영 및 FA버튼 크기 변경

Clipster/Clipster/Domain/UseCase/Clip/DefaultSearchClipsUseCase.swift, Clipster/Clipster/Domain/UseCase/Folder/DefaultSearchFoldersUseCase.swift
close #608 
Reactor에서 공백 제거한 문자열을 넘겨주고 있지만,
방어적 프로그래밍 차원에서 UseCase에서도 공백 제거한 문자열을 사용하도록 수정
=> Search~UseCase 공백 제거한 문자열 사용하도록 수정

Clipster/Clipster/App/DIContainer/DIContainer.swift, Clipster/Clipster/Presentation/Coordinator/MyPage/MyPageCoordinator.swift, Clipster/Clipster/Presentation/Protocol/SelectableOption.swift, Clipster/Clipster/Presentation/Resource/Icon.xcassets/RadioSelected.imageset/Contents.json, Clipster/Clipster/Presentation/Resource/Icon.xcassets/RadioSelected.imageset/RadioSelected.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/RadioUnselected.imageset/Contents.json, Clipster/Clipster/Presentation/Resource/Icon.xcassets/RadioUnselected.imageset/RadioUnselected.svg, Clipster/Clipster/Presentation/Scene/Common/Cell/RadioCell.swift, Clipster/Clipster/Presentation/Scene/MyPage/Model/Detail/ThemeOption+Extension.swift, Clipster/Clipster/Presentation/Scene/MyPage/Reactor/MyPageReactor.swift, Clipster/Clipster/Presentation/Scene/MyPage/ViewController/MyPageViewController.swift, Clipster/Clipster/Presentation/Scene/SingleOptionSelector/ViewController/SingleOptionSelectorViewController.swift
close #574 
- 테마 선택 모달 추가
- 테마 변경마다 UI업데이트 및 UseCase 호출
- 로그아웃, 회원탈퇴시에만 ScrollToTop 되도록 변경
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/82a6616d-819b-45a4-824a-db226db48c1b" width="250px"> |
- 테마 변경 UI업데이트 할때 currentState에서 테마아이템을 직접 찾아서 변경하고있는데 좀 더 좋은 방법 있으면 피드백 부탁드릴게요
=> 테마 선택 모달 구현

Clipster/Clipster/App/DIContainer/DIContainer.swift, Clipster/Clipster/Presentation/Scene/Folder/Reactor/FolderReactor.swift
close #623 
- FolderView 폴더, 클립 정렬 적용
- make 메서드 네이밍 수정
- make 메서드 네이밍 수정이 반영되면, 아마 DIContainer에서 HomeReactor를 초기화하는 과정에서 빌드 오류가 생길 것 같습니다. (어떤게 먼저 merge 될지 아직 모르겠어서요 참고해주세요!)
=> FolderView 폴더, 클립 정렬 적용

Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
close #632 
- Left/Right StackView의 alignment가 .center이기 때문에 내부에서 StackView의 높이를 정할 수 없음
-> 따라서 높이를 48로 지정하여 해결
- 스택뷰 비어있을경우 너비 모호함 문제 발생
-> 비어있을경우 hidden 처리
- 일단 문제 없는지 확인은 마쳤지만 혹시 모르니 맡으신 화면 View Hierarchy 확인 부탁드립니다
=> 공통 네비게이션 뷰 레이아웃 경고 해결

Clipster/Clipster/App/Coordinator/App/AppCoordinator.swift, Clipster/Clipster/App/DIContainer/DIContainer.swift, Clipster/Clipster/App/Source/SceneDelegate.swift, Clipster/Clipster/Presentation/Coordinator/Home/HomeCoordinator.swift, Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
close #659 
- Share Extension에서 바로 저장할 수 있는 기능이 구현되기 이전, 메인 앱 진입 -> EditClipView로 화면 전환될 때 관련 로직을 모두 제거하지 않았던 것 같습니다.
=> ShareExtension에서 메인 앱 진입 관련 로직 제거

Clipster/Clipster/Presentation/Resource/Icon.xcassets/Home.imageset/Contents.json, Clipster/Clipster/Presentation/Resource/Icon.xcassets/Home.imageset/Home.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/Home.imageset/home.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/HomeSelected.imageset/Contents.json, Clipster/Clipster/Presentation/Resource/Icon.xcassets/HomeSelected.imageset/home-selected-dark.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/HomeSelected.imageset/home-selected.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/Search.imageset/Contents.json, Clipster/Clipster/Presentation/Resource/Icon.xcassets/Search.imageset/Search.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/Search.imageset/search.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/SearchSelected.imageset/Contents.json, Clipster/Clipster/Presentation/Resource/Icon.xcassets/SearchSelected.imageset/search-selected-dark.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/SearchSelected.imageset/search-selected.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/User.imageset/Contents.json, Clipster/Clipster/Presentation/Resource/Icon.xcassets/User.imageset/User.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/User.imageset/user.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/UserSelected.imageset/Contents.json, Clipster/Clipster/Presentation/Resource/Icon.xcassets/UserSelected.imageset/user-selected-dark.svg, Clipster/Clipster/Presentation/Resource/Icon.xcassets/UserSelected.imageset/user-selected.svg, Clipster/Clipster/Presentation/Scene/TabBar/SubView/TabBarView.swift
close #685
* 탭바 Selected 상태 아이콘 변경
| iPhone 16 Pro | <img src="https://github.com/user-attachments/assets/4768572d-8f67-4a6e-a893-5e0ab136b0cb" width="250px"> |
=> 탭바 Selected 상태 아이콘 변경
